### ISSUE TITLE
Deploying to Heroku

### ISSUE THREAD

**Issue by 1sc0** [jedireza/drywall#285]
Hey.  Thanks for this wonderful system.  I'm having some issues deploying to Heroku.  Following the instructions https://github.com/jedireza/drywall/wiki/Deploying-to-Heroku.

Everything works fine if I run it locally 

    node app.js

But I get an Application Error when deployed to Heroku (https://evening-shore-8405.herokuapp.com/).

Looking at the logs, this is what I get http://pastebin.com/TgN0gRQ6

Any help would be much appreciated!

**Comment by jedireza** [comment]
> Thanks for this wonderful system.

Thank you! :wink: 

> I'm having some issues deploying to Heroku. Following the instructions https://github.com/jedireza/drywall/wiki/Deploying-to-Heroku

Woof, we really need to update that guide.

 - - - - -

It looks like you're missing a module possibly:

```
Error: Cannot find module 'iconv-lite'
```

This could happen if your dependencies are in `devDependencies` since by default on Heroku, `npm` only installs production assets. Here are some links that may help.

 - https://github.com/jedireza/drywall/wiki/Dependency-%26-Asset-Check-ins
 - https://devcenter.heroku.com/articles/nodejs-support#customizing-the-build-process

Also, I recently updated the guide for [Aqua](https://github.com/jedireza/aqua/) about deploying to Heroku, although it's a different project, the concepts are still relevant.

 - https://github.com/jedireza/aqua/wiki/Deploying-to-Heroku

I hope this helps. Keep us posted.

**Comment by 1sc0** [comment]
Thanks for the prompt reply!  This was due to my ignorance on how to use Heroku -- 1st time using it).  I knew it was related to iconv-lite but I didn't know how to go about solving it exactly.  I had followed the instructions on https://github.com/jedireza/drywall/wiki/Dependency-%26-Asset-Check-ins even before posting this issue to no avail...  It ended up being due to a stupid global .gitignore rule (for "Icon" and turning off case sensitivity) that ignored iconv-lite on my dev environment.

For those who run into the error for deploying to Heroku.  Inside the drywall directory do a:

    npm install iconv-lite

Which will install the module inside the `node_modules` sub-directory.  Then:

    git add node_modules

It'll add everything new inside of the node_modules sub-directory.  And finally:

    git commit -m "adding additional dependencies"
    git push heroku master

And you should be good to go!

**Comment by benmarten** [comment]
This is not a great solution. I would rather move that package from devDependencies to dependencies in package.json!

**Comment by jedireza** [comment]
Hi @benmarten :wave: 

Which solution are you referring to? There are actually many ways to go about this that I mention here:
https://github.com/jedireza/aqua/wiki/Deploying-to-Heroku#dependencies-and-build-files

Is there something else you think we should mention?
