### ISSUE TITLE
Session Timeout

### ISSUE THREAD

**Issue by bendtheji** [jedireza/drywall#303]
Hello, 

I am really new to all of this and I have been trying to look for solutions but I do not quite understand how I may be able to set the time for a session before the user gets a warning and gets logged out after some more time. I have tried setting the cookie's maxAge within the app.js file but it didn't work. Would really appreciate any help.

Regards.

**Comment by jedireza** [comment]
Thanks for creating an issue.

> I am really new to all of this...

Welcome :wink:

> I have tried setting the cookie's maxAge within the app.js file but it didn't work. Would really appreciate any help.

Would you be willing to describe your desired result in more detail?

**Comment by bendtheji** [comment]
Hi there thanks for replying!

Well, what I have in mind would be that after perhaps 20 minutes of inactivity from the user, a warning message appears on screen asking the user whether he would like to continue the session or log out, and then after an additional 5/10 minutes, the application automatically logs out the user. I have looked for code samples online but I'm not very sure of how I can integrate it into the framework.

Regards.

**Comment by jedireza** [comment]
Great question. I don't know. I've seen this type of feature before, but never implemented one myself. Let's try to figure it out.

The first thing to know is that we use [`express-session`](https://github.com/expressjs/session), which is what's creating the `connect.sid` cookie. That cookie ties the user back to a session on the server. I looked at the `express-session` README and searched the page for "expire" found this in their docs:

> By default `cookie.maxAge` is `null`, meaning no "expires" parameter is set so the cookie becomes a browser-session cookie. When the user closes the browser the cookie (and session) will be removed.

And out of the box, Drywall isn't setting the `cookie.maxAge` option, so it's using the default. The first step is to supply that value. So in [`/app.js`](https://github.com/jedireza/drywall/blob/8e38473d97a74b39e764f287ebfc7c50b0f3aca6/app.js#L50-L55) I added an extra `cookie` option:

```js
app.use(session({
  resave: true,
  saveUninitialized: true,
  secret: config.cryptoKey,
  store: new mongoStore({ url: config.mongodb.uri }),
  cookie: { maxAge: 60000 } // woot!
}));
```

After that I cleared my cookies and logged in again. Then I saw an expiration date in my web developer inspector. It looks something like this:

![screen shot 2015-06-30 at 11 59 50 pm](https://cloud.githubusercontent.com/assets/979929/8449215/5a577134-1f84-11e5-8d26-6a5d370edd4c.png)

So 60,000 milliseconds = 60 seconds = a one minute cookie. And I tested it. I didn't make any further requests until after the expiration time and bam, on my next request I got sent back to the login. Perfect, all we need to do now is get that expiration date in JavaScript and show a notice to the user if that time is approaching in the window that we think is reasonable.

So I searched Google: [javascript get cookie expiration](https://www.google.com/search?q=javascript+get+cookie+expiration)

I tend to favor StackOverflow results since the content quality is high answers usually help. And the top two results said it all: you can't get the expiration date of a cookie in JavaScript. :cry: 

Well hmm... we could... send a cookie with each request that stored how long that session has before it expires. We can do that by adding a cookie inside [our top level middleware](https://github.com/jedireza/drywall/blob/8e38473d97a74b39e764f287ebfc7c50b0f3aca6/app.js#L61-L68):

```js
// response locals
app.use(function(req, res, next) {
  res.cookie('_csrfToken', req.csrfToken());
  res.cookie('_sessionExpires', req.session.cookie.maxAge); // woohoo!
  res.locals.user = {};
  res.locals.user.defaultReturnUrl = req.user && req.user.defaultReturnUrl();
  res.locals.user.username = req.user && req.user.username;
  next();
});
```

Now in the browser we can get that value and use it.

__Keep in mind__: The `_sessionExpires` cookie's value is the time remaining (in milliseconds) on the server. So in the browser, we need to start acting on it right away on the first page load and keep it updated for each XHR (ajax) that's made.

To get the cookie value after each XHR request, we need to tap into each XHR call somehow. Luckily we can do that in [our global `ajaxStop` function](https://github.com/jedireza/drywall/blob/2deee7aa3d18d9b92391abef05d82ed9cb3a5a44/public/layouts/core.js#L15) (it's a jQuery helper). We'd need to add logic to that function in order to get that cookie and do something with it's value:

```js
$(document).ajaxStop(function () {
  $('.ajax-spinner').hide();

  // access _sessionExpires value inside the document.cookie string
});
```

And since after the time expires the next request will take the user to the login page, we just need to refresh the page like so:

```js
location.reload();
```

:tada: Cool! Now we know one way to do it. I hope that helps and good luck with your project.
