### ISSUE TITLE
Unable to start using npm start

### ISSUE THREAD

**Issue by abhishekb21** [jedireza/drywall#329]
Error when running npm start after checking out code on MAC OSX 10.10:

```
Running "less:layouts" (less) task
>> NameError: variable @dl-horizontal-breakpoint is undefined in public/vendor/bootstrap/less/type.less on line 214, column 22:
>> 213 
>> 214   @media (min-width: @dl-horizontal-breakpoint) {
>> 215     dt {
Warning: Error compiling public/less/bootstrap-build.less Use --force to continue.

Aborted due to warnings.
```

```
npm version
{ Drywall: '0.16.4',
  npm: '3.3.12',
  ares: '1.10.1-DEV',
  http_parser: '2.6.0',
  icu: '56.1',
  modules: '47',
  node: '5.1.1',
  openssl: '1.0.2e',
  uv: '1.7.5',
  v8: '4.6.85.31',
  zlib: '1.2.8' }
```

grunt -v fails, grunt copy -v passes.

**Comment by yeelan0319** [comment]
@abhishekb21 
I ran into the same issue today.
The reason I found is because the variables.less file is not loaded during the less build process, so it cannot find the dl-horizontal-breakpoint and result in the problem.

I updated ```/public/less/bootstrap-build.less``` and inserted ```@import "../vendor/bootstrap/less/variables.less";``` at line 10, which solve the problem. Hope this may help you as well:)

**Comment by jedireza** [comment]
Thanks for opening an issue. This happens sometimes when Bootstrap adds new variables. Those new variables just need to be defined in `/public/less/bootstrap-vars.less`.

**Comment by abhishekb21** [comment]
@yeelan0319 
Thanks. I got it working with your fix.
