### ISSUE TITLE
User Groups?

### ISSUE THREAD

**Issue by marcnicholas** [jedireza/drywall#341]
I'd like to add something similar to the Admin Groups functionality but at the User level. In other words, be able to assign a User to a group or multiple groups. This could be an arbitrary text field, or a pull up from the database.

I'm a bit lost as to where to start as I have zero Backbone experience. Any pointers? It seems like this might be of interest to other users too.

Thanks.

**Comment by jedireza** [comment]
Thanks for opening an issue. I suggest reading through the wiki for some background on the existing setup. Specifically: https://github.com/jedireza/drywall/wiki/Users%2C-Roles-%26-Groups#roles--vs--groups

Since Backbone is used for the front-end UI, it's a smaller battle compared to the shema changes you'll need to make to effect the change you're talking about.

From my experience it makes more sense for groups to be on the role lever and not the user level.

What are you trying to accomplish?

**Comment by marcnicholas** [comment]
Okay, thanks for the pointer to the wiki. The schemas make more sense to me now.

I basically want to do what you've alluded to at the bottom of the page: AccountGroups tied to Accounts. I'd like to "tag" Accounts with access to particular assets (which will be handled outside of Drywall). Maybe I could even just extend the Accounts schema with a String array for the assets each account is allowed access to. Probably doesn't need to be more complicated than that for my use-case.

Thanks!

**Comment by jedireza** [comment]
> I'd like to "tag" Accounts with access to particular assets (which will be handled outside of Drywall). Maybe I could even just extend the Accounts schema with a String array for the assets each account is allowed access to. Probably doesn't need to be more complicated than that for my use-case.

That sounds much more reasonable :+1:
