### ISSUE TITLE
bypass confirm email

### ISSUE THREAD

**Issue by scottmont** [jedireza/drywall#355]
trying to bypass the confirm email but the createaccount workflow doesn't seem to run.

Can't I just call the createaccount here instead?

     if (!user) {
        req.session.socialProfile = info.profile;
        res.render('signup/social', { email: info.profile.emails && info.profile.emails[0].value || '' });

**Comment by jedireza** [comment]
There is a config setting that toggles if email verification is required. It's off by default.
https://github.com/jedireza/drywall/blob/520444296dd60e42702f793c181a53d2de15d98c/config.example.js#L16

Also, even if it's on, when you use a 3rd party login during signup, it'll skip making the user verify their email since using one of those services is verification enough.

**Comment by scottmont** [comment]
Thank you for answering.  
I have misled you I meant to confirmation webpage not the confirmation email.

I put this function in the public/views/signup/social.js file to help me skip by it

app.SignupView = Backbone.View.extend({
    el: '#signup',
    template: _.template( $('#tmpl-signup').html() ),
    events: {
      'submit form': 'preventSubmit',
      'keypress [name="password"]': 'signupOnEnter',
      'click .btn-signup': 'signup'
    },
    initialize: function() {
      this.model = new app.Signup();
      this.model.set('email', $('#data-email').text());
      this.listenTo(this.model, 'sync', this.render);
      this.render();
      this.autosignup();
    },

 autosignup: function() {
     this.signup();
    },

**Comment by jedireza** [comment]
I see. I wouldn't suggest skipping this step.

 1. Not all the 3rd parties auth providers send back an email address (ex: Twitter), so the user needs to provide one.
 2. Also this confirmation screen helps ensure users have a unique username. By default it's not impossible for there to be username conflicts.

Could you describe your goals or what flow would be ideal?

**Comment by scottmont** [comment]
Thank you for answering.

I will only have github and facebook as options.  I want to skip right by the email and have it not show at all.

As a side question ...if i put this behind nginx where can I set the host information as it's redirecting to the internal ip.

**Comment by jedireza** [comment]
Ok so in that case one thing you could do is:

 - in the [`signupGitHub`](https://github.com/jedireza/drywall/blob/520444296dd60e42702f793c181a53d2de15d98c/views/signup/index.js#L225-L226) and [`signupFacebook`](https://github.com/jedireza/drywall/blob/520444296dd60e42702f793c181a53d2de15d98c/views/signup/index.js#L253-L254) handlers, before we render the `signup/social` view... you should be performing the logic that happen inside of the [`signupSocial`](https://github.com/jedireza/drywall/blob/520444296dd60e42702f793c181a53d2de15d98c/views/signup/index.js#L330) handler after a a user submits the form on that confirmation screen.
 - that logic includes `duplicateUsernameCheck`, `duplicateEmailCheck`, `createUser`, `createAccount`, `sendWelcomeEmail` and finally `logUserIn`.
 - then if either duplicate checks fail, you'd render the `signup/social` view as before
 - if both checks pass, you'd `createUser`, `createAccount`, `sendWelcomeEmail`, `logUserIn` and finally just redirect to the `/account/` url instead of rendering the `social/signup` view. 

Because you'll have to do these things twice (for Facebook and Github), it'll be best to pull those routines out into functions for reuse. Sounds like a nice sized customization for your project. I hope that works out well. Happy hunting.
