### ISSUE TITLE
Just figuring it out

### ISSUE THREAD

**Issue by sirEgghead** [jedireza/drywall#356]
Hey, I appreciate all the hard work you've done on this project.  I like the looks of it.

This may or may not be the proper place to ask for help, but I don't know where else to go.  I did some research online first.  :)

I have an angular app that I've been working on and now I'm trying to integrate it with drywall.  I'm kinda learning Jade at the same time.  :)  Anyway, I'll lay out my files for this new function and then I'll give you my results.

### My Schema
```
'use strict';

exports = module.exports = function(app, mongoose){
  var requestSchema = new mongoose.Schema({
    title: {
      type: String,
      required: true
    },
    type: {
      type: String,
      required: true
    },
    user: {
      type: String,
      required: true
    }
  });
  app.db.model('Request', requestSchema);
};
```

### index.js
```
'use strict';

exports.init = function(req, res){
  res.render('requests/index');
};

exports.find = function(req, res, next){
  req.query.title = req.query.title ? req.query.title : '';
  req.query.type = req.query.type ? req.query.type : '';
  req.query.user = req.query.user ? req.query.user : '';
  
  res.render('requests/index', { title: 'myTitle', type: 'someType', user: 'me'});
};
```

### index.jade
```
extends ../../layouts/default

block head
  title Requests

block neck
  link(rel='stylesheet', href='/views/requests/index.min.css?#{cacheBreaker}')

block body
  div.row
    div.col-sm-6
      div#header
      div#filters
      div#results-table
      div#results-paging
      div.page-header
        h1 Requests
      table(class="table table-striped")
        thead
          th Title
          th Type
          th User
          th Delete
        tbody#results-rows
          tr(ng-repeat="request in requests")
            td
              a(ui-sref="editRequest({id:request._id})") Request
            td= type
            td <%= user %>
            td Delete
```

So my results:

![image](https://cloud.githubusercontent.com/assets/6648625/14055723/8b01a570-f2ba-11e5-90f8-23f8084ed67d.png)

I figured out that my ui-router stuff doesn't fit.  So ignore the "a(ui-sref" stuff for now. :)  For the 3 table datas after that, I got "someType" for the first one, which was a great test/proof of concept.  The second one didn't work as I'd hoped.  It displays "<%= user %>" directly on my page.  And the third td is obviously just a placeholder for now.

I got the "<%= user %>" part from admin/users and the like.  And in the js file, the init function can be ignored.  I had that as my first proof of concept.  Just taking it one step at a time.  :)  Inside find function of the js file though, the first three lines I kind of just have there.  Sort of a copy/paste from one of your js files like admin/users etc.  I'm not sure how to finish out my render, however.

I do have the data in my drywall database in a collection called "requests".  It is built like the schema listed here.  It is the same schema used in my working application, actually.  :)

Anyway, I'd certainly appreciate any help given.  I'd love to learn to use this effectively!  :D

**Comment by jedireza** [comment]
Thanks for opening an issue. Warning: I don't have any experience with Angular myself.

> Hey, I appreciate all the hard work you've done on this project. I like the looks of it.

Thanks for the kind words.

> I have an angular app that I've been working on and now I'm trying to integrate it with drywall.

Typically you'd start with Drywall and start customizing. Integrating it with another app may could turn into a lot of work.

- - - - -

Since you're not using backbone, may I suggest checking out [Frame](https://github.com/jedireza/frame/). Frame is the API from Drywall, build with Hapi instead of Express, it doesn't have a front-end (you can build everything in Angular if you like) and it has decent test coverage.

@Silom made a front-end for it with Angular a while back called [ngFrame](https://github.com/Silom/ngFrame).

**Comment by sirEgghead** [comment]
Thank you for your quick response!  Much appreciated!

I haven't ever used backbone or frame.  I'll start taking a look at them now!

> Typically you'd start with Drywall and start customizing. Integrating it with another app may could turn into a lot of work.

Well really it's just a single form page and a results page.  So let's consider it building anew on Drywall rather than integrating something existing.  :)  I feel like what I've done so far is very close to actually displaying my the data from my Mongodb.  While I'm looking over the documentation you've pointed me to so far, would you mind looking at the simple files I've pasted here and tell me if I'm close or just totally hosed it?  lol

Thanks again!

**Comment by sirEgghead** [comment]
Whoops, horrible misclick.  Sorry, long day at work.  :)

**Comment by jedireza** [comment]
There are quite a few technologies in Drywall to get familiar with:
https://github.com/jedireza/drywall#technology

Once you're comfortable with them though, it's easier to understand how they connect and where to make changes.

We don't have tutorials/guides on these different technologies, they're well documented online. But we do have a a set of wiki pages for Drywall specific stuff:
https://github.com/jedireza/drywall/wiki

To build up an understanding, I'd suggest:

 - first get to know our Gruntfile and how the client side files are produced (Grunt)
 - then understand the client and server sides of the contact page (Jade and Backbone)
 - then move on to the login
 - then start taking on the admin screens like statuses

Your mileage may vary.

- - - - -

These days, personally, I'd reach for Frame instead of Drywall and build the front-end in something besides Backbone. I'm closing this issue for now. I hope some of this helps inspire the right path forward.

Don't hesitate to ask more questions. :+1:
