### ISSUE TITLE
How to get going, the basics and Android & iOS auth

### ISSUE THREAD

**Issue by utkarshns** [jedireza/drywall#383]
Since no documentation exists for Drywall, what is the best way to get a good grip around Drywall's core functioning to add/remove/modify features?
Also, what would be the best way to make it work with Android/iOS?

Thanks 😄

**Comment by jedireza** [comment]
Thanks for opening an issue.

> Since no documentation exists for Drywall, what is the best way to get a good grip around Drywall's core functioning to add/remove/modify features?

Our [README](https://github.com/jedireza/drywall/blob/master/README.md) covers installation, setup and running the app. The [wiki](https://github.com/jedireza/drywall/wiki) has more about the inner workings.

Remember that Drywall is just a boilerplate, built with other modules/technologies. The documentation of those tools plus what we have here should be sufficient. After digging in and exploring/understanding more of the code base, by all means please open specific issues and suggestions.

> Also, what would be the best way to make it work with Android/iOS?

I'm not sure exaclty what you mean. You could customize the API to support mobile/desktop app clients, but those decisions aren't baked in. I also suggest checking out [Frame](https://github.com/jedireza/frame/), which is the Drywall API, built with hapi instead of express, has much better testing and doesn't come with all the front-end stuff.

**Comment by utkarshns** [comment]
Thanks a lot, I will go through the recommended links.
